"""Frontend hosting.

Two modes, chosen automatically:

  * **Built**, if `frontend/dist/index.html` exists (i.e. `npm run build` has
    been run), that production bundle is served. This is the deployment path.

  * **Source**, otherwise the React + TypeScript source under `frontend/src`
    is served as-is and compiled in the browser by the loader in `index.html`.
    This exists so the POC is runnable on a machine with Python but no Node.js;
    it is a development convenience, not the production story.

Either way the same `.tsx` sources are the single copy of the UI, so moving to a
real Vite build never means rewriting components.
"""
from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles

from ..config.logging_conf import get_logger
from ..config.settings import Settings

log = get_logger(__name__)

#: Extensions the source-mode server will hand out. Anything else is refused,
#: so a stray .env or .db inside frontend/ can never be served.
SERVABLE_SUFFIXES = {
    ".html", ".js", ".mjs", ".jsx", ".ts", ".tsx", ".css", ".json",
    ".svg", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".woff", ".woff2",
}

MEDIA_TYPES = {
    ".tsx": "text/plain; charset=utf-8",
    ".ts": "text/plain; charset=utf-8",
    ".jsx": "text/plain; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".html": "text/html; charset=utf-8",
}


def mount_frontend(app: FastAPI, settings: Settings) -> None:
    frontend_dir = settings.frontend_dir
    dist_dir = frontend_dir / "dist"

    if (dist_dir / "index.html").is_file():
        _mount_built(app, dist_dir)
        return

    if settings.is_hosted:
        # Startup refuses this configuration, so reaching here means the guard
        # was bypassed. Serve nothing rather than source under a policy that
        # cannot execute it.
        log.error(
            "hosted mode without a built frontend; serving API only",
            extra={"event": "frontend.not_built", "path": str(dist_dir)},
        )
        return

    if not (frontend_dir / "index.html").is_file():
        log.warning(
            "no frontend found; API only",
            extra={"event": "frontend.missing", "path": str(frontend_dir)},
        )
        return

    _mount_source(app, frontend_dir)


def _mount_built(app: FastAPI, dist_dir: Path) -> None:
    app.mount("/", StaticFiles(directory=str(dist_dir), html=True), name="frontend")
    log.info("serving built frontend", extra={"event": "frontend.dist", "path": str(dist_dir)})


def _mount_source(app: FastAPI, frontend_dir: Path) -> None:
    root = frontend_dir.resolve()

    @app.get("/api/__frontend/modules", include_in_schema=False)
    def module_manifest() -> JSONResponse:
        """List the TS/TSX modules the in-browser loader must fetch.

        Generated by scanning `src/` so adding a component never means editing
        a hand-maintained list.
        """
        source_root = root / "src"
        modules = sorted(
            path.relative_to(root).as_posix()
            for path in source_root.rglob("*")
            if path.is_file()
            and path.suffix in {".ts", ".tsx"}
            # Test files import vitest and are never part of the running app.
            and ".test." not in path.name
            and ".spec." not in path.name
        )
        return JSONResponse({"modules": modules})

    @app.get("/", include_in_schema=False)
    def index() -> FileResponse:
        return FileResponse(root / "index.html", media_type="text/html; charset=utf-8")

    @app.get("/{file_path:path}", include_in_schema=False)
    def static_file(file_path: str):
        target = _safe_resolve(root, file_path)
        if target is None:
            # Unknown paths fall back to the SPA shell so client-side routes work.
            return FileResponse(root / "index.html", media_type="text/html; charset=utf-8")

        media_type = MEDIA_TYPES.get(target.suffix.lower())
        if target.suffix.lower() in {".tsx", ".ts", ".jsx"}:
            # Served as text: the browser loader compiles these, it must not try
            # to execute them as JavaScript modules.
            return PlainTextResponse(
                target.read_text(encoding="utf-8"), media_type=media_type
            )
        return FileResponse(target, media_type=media_type)

    log.info(
        "serving frontend source (in-browser compile; run `npm run build` for production)",
        extra={"event": "frontend.source", "path": str(root)},
    )


def _safe_resolve(root: Path, file_path: str) -> Path | None:
    """Resolve a request path inside `root`, or None if it is not servable."""
    if not file_path or file_path.startswith("api/"):
        return None
    try:
        candidate = (root / file_path).resolve()
    except (OSError, RuntimeError, ValueError):
        return None

    # Path traversal guard: the resolved path must stay under the frontend root.
    try:
        candidate.relative_to(root)
    except ValueError:
        return None

    if not candidate.is_file() or candidate.suffix.lower() not in SERVABLE_SUFFIXES:
        return None
    return candidate
